name: Validate Docker Compose files
on:
  workflow_dispatch:
  push:

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/base-builder:ubuntu.0.1.0.b53
    steps:
      - uses: actions/checkout@v4
      - name: Validate Docker Compose files
        run: |
          docker compose -f demo/compose.yml config
          docker compose -f event-forwarding/compose.yml config
